regulator: rpm-smd-regulator: Add snapshot of rpm-smd-regulator driver
This is a snapshot of the rpm-smd-regulator driver taken from qcom-6.6
branch commit aec6d1c78682 ("regulator: rpm-smd-regulator: Add support
for debugfs control").

Include the of_platform.h header to fix the compilation error:
"error: call to undeclared function 'of_platform_populate';
ISO C99 and later do not support implicit function declarations".

Update the remove callback to have a void return value to fix
compilation error: "error: incompatible function pointer types
initializing 'void (*)(struct platform_device *)' with an
expression of type 'int (struct platform_device *)'".

Change-Id: I5320515b2ffac96cee2ddb3053f6baece3af2b97
Signed-off-by: Swetha Chikkaboraiah <quic_schikk@quicinc.com>
Signed-off-by: Shilpa Suresh <c_sbsure@qti.qualcomm.com>